17 evaluar la posibilidad de implementar un mejor algoritmo de creación de grafos
sebas-tcotd/grupo1-ed-2020-I-unmsm-fisi pull request #18
Opened 2023-07-10 17:58 UTC by Maurck

2023-07-10 18:02 UTC, Maurck commented
![image](https://github.com/sebas-tcotd/graphy/assets/49370261/c167b6ad-ffc0-41fd-ae27-8fd64974791e)

2023-07-10 18:38 UTC, sebas-tcotd commented
Está sucediendo el siguiente error al momento de realizar el build:
`src/utils/setModalType.tsx(7,3): error TS2724: '../common/components' has no exported member named 'LayoutOptionsModalBodyProps'. Did you mean 'LayoutOptionsModalBody'?`

2023-07-10 18:40 UTC, sebas-tcotd requested changes
Need some changes inside `src\utils\setModalType.tsx`

2023-07-10 18:43 UTC, sebas-tcotd commented on src/store/slices/graph/graphSlice.ts
> +    layout: LayoutTypes.CIRCULAR,
Es preferible dejar los datos de `complexity` y `layout` como `undefined` ya que para el momento en que se crea la aplicación, el grafo no existe. Tener estas propiedades daría a entender que el grafo existe dentro del store cuando aún no ha sido creado

2023-07-10 21:11 UTC, Maurck commented on src/store/slices/graph/graphSlice.ts
> +    layout: LayoutTypes.CIRCULAR,
Aunque el grafo tecnicamente aun no existe, dejarlos como undefined provoca un bug en el que la aplicación no puede procesar el primer intento de creacion del grafo, se tendrá que cambiar el flujo para tener eso en cuenta

2023-07-11 00:32 UTC, sebas-tcotd approved these changes

2023-07-11 00:38 UTC, merged